# Generated by Django 3.0.6 on 2020-07-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cal', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='groupEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.MyGroup'),
        ),
    ]
