# Generated by Django 3.0.6 on 2020-07-28 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('listId', models.AutoField(primary_key=True, serialize=False)),
                ('listName', models.CharField(max_length=200, unique=True, verbose_name='List Name')),
                ('listCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listGroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.MyGroup')),
            ],
        ),
        migrations.CreateModel(
            name='MyListItems',
            fields=[
                ('listitemId', models.AutoField(primary_key=True, serialize=False)),
                ('listItemName', models.TextField(verbose_name='New List Item')),
                ('listMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_List.MyList')),
            ],
        ),
    ]
